name: Build executables for a release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up swap space
        uses: thejerrybao/setup-swap-space@v1
        with:
          swap-size-gb: 10

      - name: Set the timezone to New Zealand
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Pacific/Auckland'

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Monitor Runner
        uses: tsviz/actions-runner-telemetry@v1

      - name: Install packages
        run: |
          bun install

      - name: Build application
        run: |
          bun run -b build

      - name: Compile built application to standalone executables
        run: |
          bun run scripts/build.executables.ts
